version: '3'
services:
    strapi_dronesite:
        image: rawestmoreland/dronesite_backend:dev
        volumes:
            - ./backend:/srv/app
        ports:
            - '1336:1336'
    # dronesite_frontend_dev:
    #     image: rawestmoreland/dronesite_frontend:dev
    #     depends_on:
    #         - strapi_dronesite
    #     ports:
    #         - '3001:3001'
